version: "3.3"

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - ./:/root/redis
      - ./:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=password
      - REDIS_PORT=6380
      - REDIS_DATABASES=16
